spring:
  config:
    import: optional:file:.env[.properties]
  application:
        name: ${SPRING_APP_NAME:spring-sec}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3316/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}

logging:
  level:
    org.springframework.security: TRACE
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5.5level) %red([%20.20thread]) %yellow(%-40.40logger) - %msg%n}
