spring:
    config:
      activate:
        on-profile: prod
    jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.springframework.security: ERROR
